# Generated by Django 4.0.6 on 2022-07-20 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mail',
            new_name='Parcel',
        ),
    ]
