# Generated by Django 4.0.6 on 2022-07-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_pickup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='pickup',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='pickup',
            name='date',
            field=models.DateField(verbose_name='Pick up Date'),
        ),
    ]
